[workspace]

members = [
    "drink",
    "drink-cli",
]

exclude = [
    "examples/counter",
    "examples/flipper",
]

[workspace.package]
authors = ["Cardinal"]
edition = "2021"
homepage = "https://github.com/Cardinal-Cryptography/drink"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/Cardinal-Cryptography/drink"
version = "0.1.0"

[workspace.dependencies]
anyhow = { version = "1.0.71" }
clap = { version = "4.3.4" }
crossterm = { version = "0.26.0" }
contract-transcode = { version = "3.0.1" }
parity-scale-codec = { version = "3.6.0" }
ratatui = { version = "0.21.0" }
scale-info = { version = "2.5.0" }

# Substrate dependencies

frame-support = { version = "21.0.0" }
frame-system = { version = "21.0.0" }
pallet-balances = { version = "21.0.0" }
pallet-contracts = { version = "20.0.0" }
pallet-contracts-primitives = { version = "23.0.0" }
pallet-timestamp = { version = "20.0.0" }
sp-core = { version = "20.0.0" }

# Local dependencies

drink = { path = "drink" }
