[workspace]
resolver = "2"

members = [
    "drink",
    "drink-cli",
]

exclude = [
    "examples/counter",
    "examples/flipper",
    "examples/cross-contract-call-tracing",
]

[workspace.package]
authors = ["Cardinal"]
edition = "2021"
homepage = "https://github.com/Cardinal-Cryptography/drink"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/Cardinal-Cryptography/drink"
version = "0.1.8"

[workspace.dependencies]
anyhow = { version = "1.0.71" }
clap = { version = "4.3.4" }
contract-build = { version = "3.0.1" }
contract-transcode = { version = "3.0.1" }
crossterm = { version = "0.26.0" }
parity-scale-codec = { version = "3.4" }
parity-scale-codec-derive = { version = "3.4" }
ratatui = { version = "0.21.0" }
scale-info = { version = "2.5.0" }
thiserror = { version = "1.0.40" }
wat = { version = "1.0.71" }

# Substrate dependencies

frame-support = { version = "22.0.0" }
frame-system = { version = "22.0.0" }
pallet-balances = { version = "22.0.0" }
pallet-contracts = { package = "pallet-contracts-for-drink", version = "21.0.3" }
pallet-contracts-primitives = { version = "25.0.0" }
pallet-timestamp = { version = "21.0.0" }
sp-core = { version = "22.0.0" }
sp-externalities = { version = "0.20.0" }
sp-runtime-interface = { version = "18.0.0" }

# Local dependencies

drink = { version = "0.1.7", path = "drink" }
