[package]
name = "drink-cli"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
sp-runtime = { workspace = true }

drink = { workspace = true }
