---
name: Rust checks

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  main:
    name: Run check, test and lints
    runs-on: drink-runner
    env:
      CARGO_INCREMENTAL: 0
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: Cardinal-Cryptography/github-actions/install-rust-toolchain@v1
        with:
          targets: wasm32-unknown-unknown
          components: clippy rustfmt

      - name: Add rust-src
        shell: bash
        run: rustup component add rust-src

      - name: Run format checks
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all

      - name: Run linter
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets -- --no-deps -D warnings

      - name: Run unit test suite
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Run tests for examples
        shell: bash
        run: make test_examples
